- name:  "doraemon-home.github.io"
  link:  "https://github.com/doraemon-home/doraemon-home.github.io"
  repo:  "doraemon-home/doraemon-home.github.io"
  intro: "这里准备了各种道具，来帮助小伙伴们化解身边的种种困难问题。"

- name:  "blockchain"
  link:  "https://github.com/dvf/blockchain"
  repo:  "dvf/blockchain"
  intro: "Learn Blockchains by Building One"

- name:  "pyenv"
  link:  "https://github.com/pyenv/pyenv"
  repo:  "pyenv/pyenv"
  intro: "Python版本管理工具"

- name:  "avue"
  link:  "https://github.com/nmxiaowei/avue"
  repo:  "nmxiaowei/avue"
  intro: "基于json可配置化去开发界面，节约开发成本和提高开发效率"

- name:  "doraemon"
  link:  "https://github.com/TesterlifeRaymond/doraemon"
  repo:  "TesterlifeRaymond/doraemon"
  intro: "接口自动化测试工具"

